on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
env:
  CLUSTER_NAME: actions
  CLUSTER_RESOURCE_GROUP: actions
  NAMESPACE: default
  REPO: babuactions
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install helm
    - name: build
      run: |
        az acr build --image sampleapp:latest --registry ${{ env.REPO }} --file Dockerfile .

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        
    - name: deploy
      env:
        CLUSTER_RESOURCE_GROUP_NAME: ${{ env.CLUSTER_RESOURCE_GROUP }}
        CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
      run: |
        az aks get-credentials \
          --resource-group $CLUSTER_RESOURCE_GROUP \
          --name $CLUSTER_NAME \
          --overwrite-existing
        helm upgrade -i vote-app azure-vote-front/ --set image.repository=${{ env.REPO }}.azurecr.io/sampleapp --set image.tag=latest --wait
        kubectl get services -o wide
        
